CREATE TABLE `deal_terms_confirmed` (
	`id` text PRIMARY KEY NOT NULL,
	`show_id` text NOT NULL,
	`deal_type` text,
	`guarantee_amount` real,
	`artist_percentage` real,
	`percentage_basis` text,
	`expense_cap` real,
	`hospitality_cap` real,
	`walkout_threshold` real,
	`walkout_type` text,
	`tier_1_percentage` real,
	`tier_1_threshold` real,
	`tier_2_percentage` real,
	`tier_2_threshold` real,
	`bonus_1_amount` real,
	`bonus_1_trigger` text,
	`bonus_2_amount` real,
	`bonus_2_trigger` text,
	`raw_conversation` text,
	`confirmed_by` text,
	`confirmed_at` integer,
	`status` text DEFAULT 'draft' NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	FOREIGN KEY (`show_id`) REFERENCES `shows`(`id`) ON UPDATE no action ON DELETE no action
);
