import { notFound } from "next/navigation";
import { Clock, MapPin } from "lucide-react";
import { getShowDealTerms } from "@/lib/queries";
import { DealTermsView } from "@/components/deal-terms-view";
import { formatShowDateFull, relativeShowDate } from "@/lib/format";
import { ConfirmForm } from "./confirm-form";

export const metadata = {
  title: "Deal terms",
};

export default async function PublicDealTermsPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await getShowDealTerms(id);
  if (!data || !data.dealTerms) notFound();

  const { show, artist, venue, dealTerms } = data;
  const isApproved = dealTerms.status === "approved";

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-canvas">
      <div className="max-w-3xl mx-auto px-6 py-12 sm:py-16">
        <div className="mb-10">
          <div className="eyebrow text-[10px] text-ink-500 mb-3">
            Deal terms · shared by {venue?.name ?? "the venue"}
          </div>
          <h1
            className="font-display text-[44px] sm:text-[52px] font-medium text-ink-900 leading-[1.05]"
            style={{ letterSpacing: "-0.025em", fontOpticalSizing: "auto" }}
          >
            {artist?.name ?? "Show"}
          </h1>
          <div className="text-[14px] text-ink-500 mt-3 flex flex-wrap items-center gap-x-3 gap-y-1">
            <span className="text-ink-700 font-medium">
              {formatShowDateFull(show.date)}
            </span>
            <span className="text-ink-300">·</span>
            <span>{relativeShowDate(show.date)}</span>
            {(show.doorsTime || show.setTime) && (
              <>
                <span className="text-ink-200">·</span>
                <span className="flex items-center gap-1">
                  <Clock className="h-3 w-3" />
                  {show.doorsTime && <>doors {show.doorsTime}</>}
                  {show.doorsTime && show.setTime && " · "}
                  {show.setTime && <>set {show.setTime}</>}
                </span>
              </>
            )}
            {venue && (
              <>
                <span className="text-ink-200">·</span>
                <span className="flex items-center gap-1">
                  <MapPin className="h-3 w-3" />
                  {venue.name}
                  {venue.city ? `, ${venue.city}` : ""}
                  {venue.state ? `, ${venue.state}` : ""}
                </span>
              </>
            )}
          </div>
        </div>

        <div className="rounded-xl ring-1 ring-ink-200/80 bg-white p-6 mb-8">
          <div className="flex items-center justify-between mb-5">
            <div>
              <div className="text-[15px] font-semibold text-ink-900">
                Structured deal terms
              </div>
              <div className="text-[12.5px] text-ink-500 mt-0.5">
                Only fields with values are shown.
              </div>
            </div>
          </div>
          <DealTermsView terms={dealTerms} showConfirmation={isApproved} />
        </div>

        <ConfirmForm
          showId={show.id}
          initialApproved={isApproved}
          initialConfirmedBy={dealTerms.confirmedBy ?? null}
          initialConfirmedAt={
            dealTerms.confirmedAt
              ? new Date(dealTerms.confirmedAt).toISOString()
              : null
          }
        />

        <div className="mt-10 pt-6 border-t border-ink-100 text-[11.5px] text-ink-400 leading-relaxed">
          This link was generated by Greenroom for {venue?.name ?? "the venue"}.
          Confirmation is logged with your name and a timestamp.
        </div>
      </div>
    </div>
  );
}
